INSERT INTO users
VALUES (1,'Patrick','Chiang','pchiang@uw.edu','$2a$10$pwzpgYsQX2AwcH0djEqbuuHG6o1ZSSJojUg8skqBRnW/FApzNw/ay','admin');

INSERT INTO problems (problem_type, problem_name, problem_prompt, problem_expected, problem_default_before, problem_default_after, problem_check, problem_points)
VALUES ('HTML: Basic Shit',
'Headings', 
'<p>Replicate the heading in the expected panel. Create the most important heading: "PATRICK is the BEST".</p><p><a href="http://www.w3schools.com/html/html_headings.asp">Learn about headings.</a></p>',
'<h1>PATRICK is the BEST</h1>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > h1").html() == "PATRICK is the BEST"',
5), ('HTML: Basic Shit',
'More headings', 
'<p>Replicate the heading in the expected panel.</p><p><a href="http://www.w3schools.com/html/html_headings.asp">Learn about headings.</a></p>',
'<h1>top level heading</h1><h6>bottom level heading</h6><h3>mid level heading</h3>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > h1").html() == "top level heading" && $(".answer-actual > h6").html() == "bottom level heading" && $(".answer-actual > h3").html() == "mid level heading"',
10), ('HTML: Basic Shit',
'Titles', 
'<p>Write the html for creating the title of the page: HTML is fun</p><p><a href="http://www.w3schools.com/html/html_headings.asp">Learn about titles.</a></p>',
'You should create the appropriate title tag: HTML is fun',
'&lt;head&gt;',
'&lt;/head&gt;',
'$(".answer-actual > title").html() == "HTML is fun"',
5), ('HTML: Basic Shit',
'Comments', 
'<p>Comments let you insert text in code without it affecting how the program runs.</p><p><a href="http://www.w3schools.com/html/html_comments.asp">Learn about comments.</a></p>',
'Write a piece of comment saying: I will comment my code',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual").contents().filter(function(){ return this.nodeType == 8;})[0].data.replace(/ /g, "") == "I will comment my code".replace(/ /g, "")',
5), ('HTML: Basic Shit',
'Special Entities', 
'<p>Special entities are reserved characters in HTML you must use specially. Like extra spaces.</p><p><a href="http://www.w3schools.com/html/html_entities.asp">Learn about blocks.</a></p>',
'&lt;lol&gt;&cent;&nbsp; &euro;&nbsp; &copy;&nbsp; &trade;&lt;/lol&gt;',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual").html() == "&lt;lol&gt;&cent;&nbsp; &euro;&nbsp; &copy;&nbsp; &trade;&lt;/lol&gt;"',
10), ('HTML: Formatting',
'Paragraphs', 
'<p>Having fun yet? Now create some paragraphs.</p><p><a href="http://www.w3schools.com/html/html_paragraphs.asp">Learn about paragraphs.</a></p>',
'<p>paragraph 1</p><p>paragraph 2</p>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > p:nth-child(1)").html() == "paragraph 1" && $(".answer-actual > p:nth-child(2)").html() == "paragraph 2" ',
5), ('HTML: Formatting',
'Line Breaks', 
'<p>Write line breaks inside of a paragraph. Use sparingly in regular use.</p><p><a href="http://www.w3schools.com/tags/tag_br.asp">Learn about line breaks.</a></p>',
'<p>sentence 1 <br/> sentence 2</p>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > p:nth-child(1)").html().indexOf("<br>") > -1 || $(".answer-actual > p:nth-child(1)").html().indexOf("<br />") > -1 || $(".answer-actual > p:nth-child(1)").html().indexOf("<br/>") > -1',
5), ('HTML: Formatting',
'Preformatting', 
'<p>Preformatting lets you post code-like text and preserves spacing.</p><p><a href="http://www.w3schools.com/tags/tag_pre.asp">Learn about preformatted text.</a></p>',
'<pre>House  ~  of  ~  Codes</pre>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > pre:nth-child(1)").html() == "House  ~  of  ~  Codes"',
10), ('HTML: Formatting',
'Block Quotes', 
'<p><blockquote cite="Robert Wilensky">We\'ve heard that a million monkeys at a million keyboards could produce the complete works of Shakespeare; now, thanks to the Internet, we know that is not true.</blockquote</p><p><a href="http://www.w3schools.com/html/html_quotation_elements.asp">Learn about quotations.</a></p>',
'Quote something in a blockquote. I don\t care who or how. Make sure you cite it',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > blockquote:nth-child(1)").attr("cite") != null',
10), ('HTML: Formatting',
'Divs', 
'<p>These are not paragraphs. These are divs.</p><p><a href="http://www.w3schools.com/html/html_blocks.asp">Learn about blocks.</a></p>',
'<div>DIV 1</div><div>DIV 2</div><div>DIV 3</div>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > div:nth-child(1)").html() == "DIV 1" && $(".answer-actual > div:nth-child(2)").html() == "DIV 2" && $(".answer-actual > div:nth-child(3)").html() == "DIV 3"',
5), ('HTML: Links',
'Hyperlinks', 
'<p>Let\'s create a link to "http://stackoverflow.com/". Make sure your link is exact.</p><p><a href="http://www.w3schools.com/html/html_links.asp">Learn about links.</a></p>',
'<a href="http://stackoverflow.com/">Stack Overflow</a>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > a:nth-child(1)").attr("href") == "http://stackoverflow.com/" && $(".answer-actual > a:nth-child(1)").html() == "Stack Overflow"',
5), ('HTML: Links',
'Relative Hyperlinking', 
'<p>Now, let\'s link to the House of Codes logo image, but open it in a new tab. The logo image is called logo.png and sits at the root directory of the server.</p><p><a href="http://www.w3schools.com/html/html_links.asp">Learn about links.</a></p>',
'<a href="/logo.png" target="_blank">Logo in new tab</a>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > a:nth-child(1)").attr("href") == "/logo.png" && $(".answer-actual > a:nth-child(1)").attr("target") == "_blank"',
10), ('HTML: Images',
'Images', 
'<p>Images can be displayed on screen. Find an image off of the internet and display it.</p><p><a href="http://www.w3schools.com/html/html_images.asp">Learn about images.</a></p>',
'Any image here.',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > img:nth-child(1)").attr("src") != null && $(".answer-actual > img:nth-child(1)").attr("alt") != null',
5), ('HTML: Images',
'Advanced Images', 
'<p>Take an image off the internet and display it here. This time, it has to be exactly 100 pixels tall and 200 pixels wide.</p><p><a href="http://www.w3schools.com/html/html_images.asp">Learn about images.</a></p>',
'Any image here. Just make sure it fits.',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > img:nth-child(1)").attr("src") != null && $(".answer-actual > img:nth-child(1)").attr("alt") != null && $(".answer-actual > img:nth-child(1)").attr("height") == "100" && $(".answer-actual > img:nth-child(1)").attr("width") == 200',
10), ('HTML: Tables',
'Tables', 
'<p>Tables are sometimes useful for making columns and displaying data. </p><p><a href="http://www.w3schools.com/html/html_tables.asp">Learn about tables.</a></p>',
'<table><tr><td>Column 1</td><td>Column 2</td></tr><tr><td>Row 1</td><td>Item 1</td></tr><tr><td>Row 2</td><td>Item 2</td></tr></table>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > table:nth-child(1) tr:nth-child(1) td:nth-child(1)").html() == "Column 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(1) td:nth-child(2)").html() == "Column 2" && $(".answer-actual > table:nth-child(1) tr:nth-child(2) td:nth-child(1)").html() == "Row 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(2) td:nth-child(2)").html() == "Item 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(3) td:nth-child(1)").html() == "Row 2" && $(".answer-actual > table:nth-child(1) tr:nth-child(3) td:nth-child(2)").html() == "Item 2"',
10), ('HTML: Tables',
'More Tables', 
'<p>Time to add a caption/title to your table. Get on it!</p><p><a href="http://www.w3schools.com/html/html_tables.asp">Learn about tables.</a></p>',
'<table><caption>Table Title</caption><tr><td>Column 1</td><td>Column 2</td></tr><tr><td>Row 1</td><td>Item 1</td></tr><tr><td>Row 2</td><td>Item 2</td></tr></table>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > table:nth-child(1) caption").html() == "Table Title" && $(".answer-actual > table:nth-child(1) tr:nth-child(1) td:nth-child(1)").html() == "Column 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(1) td:nth-child(2)").html() == "Column 2" && $(".answer-actual > table:nth-child(1) tr:nth-child(2) td:nth-child(1)").html() == "Row 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(2) td:nth-child(2)").html() == "Item 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(3) td:nth-child(1)").html() == "Row 2" && $(".answer-actual > table:nth-child(1) tr:nth-child(3) td:nth-child(2)").html() == "Item 2"',
10), ('HTML: Tables',
'Advanced Tables', 
'<p>Ready for more table fun? Bold the headers.</p><p><a href="http://www.w3schools.com/html/html_tables.asp">Learn about tables.</a></p>',
'<table><tr><th>Column 1</th><th>Column 2</th></tr><tr><td>Row 1</td><td>Item 1</td></tr><tr><td>Row 2</td><td>Item 2</td></tr></table>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > table:nth-child(1) tr:nth-child(1) th:nth-child(1)").html() == "Column 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(1) th:nth-child(2)").html() == "Column 2" && $(".answer-actual > table:nth-child(1) tr:nth-child(2) td:nth-child(1)").html() == "Row 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(2) td:nth-child(2)").html() == "Item 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(3) td:nth-child(1)").html() == "Row 2" && $(".answer-actual > table:nth-child(1) tr:nth-child(3) td:nth-child(2)").html() == "Item 2"',
15), ('HTML: Tables',
'Complex Tables', 
'<p>Back for more? This time, we are making tables with cells that span multiple columns. Make the first row cover both rows.</p><p><a href="http://www.w3schools.com/html/html_tables.asp">Learn about tables.</a></p>',
'<table><tr><th colspan="2">Column 1 is long</th></tr><tr><td>Row 1</td><td>Item 1</td></tr><tr><td>Row 2</td><td>Item 2</td></tr></table>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > table:nth-child(1) tr:nth-child(1) th:nth-child(1)").html() == "Column 1 is long" && $(".answer-actual > table:nth-child(1) tr:nth-child(1) th:nth-child(1)").attr("colspan") == 2 && $(".answer-actual > table:nth-child(1) tr:nth-child(2) td:nth-child(1)").html() == "Row 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(2) td:nth-child(2)").html() == "Item 1" && $(".answer-actual > table:nth-child(1) tr:nth-child(3) td:nth-child(1)").html() == "Row 2" && $(".answer-actual > table:nth-child(1) tr:nth-child(3) td:nth-child(2)").html() == "Item 2"',
20), ('HTML: Lists',
'Lists', 
'<p>Lists are like tables, except with only 1 column. For now. (The question is in its own paragraph.)</p><p><a href="http://www.w3schools.com/html/html_lists.asp">Learn about lists.</a></p>',
'<p>Which one is unlike the others?</p><ul><li>HTML</li><li>CSS</li><li>Javasript</li><li>Oranges</li></ul>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > p").html() == "Which one is unlike the others?" && $(".answer-actual > ul li:nth-child(1)").html() == "HTML" && $(".answer-actual > ul li:nth-child(2)").html() == "CSS" && $(".answer-actual > ul li:nth-child(3)").html() == "Javascript" && $(".answer-actual > ul li:nth-child(4)").html() == "Oranges"',
10), ('HTML: Lists',
'Ordered Lists', 
'<p>Make the lists numbered and ordered.(The question is in its own paragraph.)</p><p><a href="http://www.w3schools.com/html/html_lists.asp">Learn about lists.</a></p>',
'<p>My favorite movies in order</p><ol><li>Avatar The Last Airbender</li><li>The Room</li><li>Catwoman</li><li>Battlefield Earth</li></ol>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > p").html() == "My favorite movies in order" && $(".answer-actual > ol li:nth-child(1)").html() == "Avatar The Last Airbender" && $(".answer-actual > ol li:nth-child(2)").html() == "The Room" && $(".answer-actual > ol li:nth-child(3)").html() == "Catwoman" && $(".answer-actual > ol li:nth-child(4)").html() == "Battlefield Earth"',
20), ('HTML: Lists',
'Listception', 
'<p>Time to make lists in lists.(The question is in its own paragraph.)</p><p><a href="http://www.w3schools.com/html/html_lists.asp">Learn about lists.</a></p>',
'<p>My least favorite movies in order</p><ol><li>The Dark Knight</li><li>Shawshank Redemption</li><li>Star Wars<ul><li>A New Hope</li><li>The Empire Strikes Back</li></ul></li><li>Lord of the Rings<ul><li>Fellowship of the Ring</li></ul></li></ol>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > p").html() == "My least favorite movies in order" && $(".answer-actual > ol li:nth-child(1)").html() == "The Dark Knight" && $(".answer-actual > ol li:nth-child(2)").html() == "Shawshank Redemption" && $(".answer-actual > ol li:nth-child(3) ul li:nth-child(1)").html() == "A New Hope" && $(".answer-actual > ol li:nth-child(3) ul li:nth-child(2)").html() == "The Empire Strikes Back" && $(".answer-actual > ol li:nth-child(4) ul li:nth-child(1)").html() == "Fellowship of the Ring"',
30);