USE node;

INSERT INTO users (first_name, last_name, email, password, user_type)
VALUES ('Patrick', 'Chiang', 'pchiang@uw.edu', '$2a$10$61lAR4cPt9yTUWWPh6vr4ObWGm0OId4bHlyOduYSiU1ks3jRAPYJq', 'admin');

INSERT INTO problems (problem_type, problem_name, problem_prompt, problem_expected, problem_default_before, problem_default_after, problem_check, problem_points)
VALUES (1,
'Headings', 
'<p>Replicate the heading in the expected panel. Create the most important heading: "PATRICK is the BEST".</p><p><a href="http://www.w3schools.com/html/html_headings.asp">Learn about headings.</a></p>',
'<h1>PATRICK is the BEST</h1>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > h1").html() == "PATRICK is the BEST"',
5), (1,
'More headings', 
'<p>Replicate the heading in the expected panel.</p><p><a href="http://www.w3schools.com/html/html_headings.asp">Learn about headings.</a></p>',
'<h1>top level heading</h1><h6>bottom level heading</h6><h3>mid level heading</h3>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > h1").html() == "top level heading" && $(".answer-actual > h6").html() == "bottom level heading" && $(".answer-actual > h3").html() == "mid level heading"',
10), (1,
'Titles', 
'<p>Write the html for creating the title of the page: HTML is fun</p><p><a href="http://www.w3schools.com/html/html_headings.asp">Learn about titles.</a></p>',
'You should create the appropriate title tag: HTML is fun',
'&lt;head&gt;',
'&lt;/head&gt;',
'$(".answer-actual > title").html() == "HTML is fun"',
5), (1,
'Paragraphs', 
'<p>Having fun yet? Now create some paragraphs.</p><p><a href="http://www.w3schools.com/html/html_paragraphs.asp">Learn about paragraphs.</a></p>',
'<p>paragraph 1</p><p>paragraph 2</p>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > p:nth-child(1)").html() == "paragraph 1" && $(".answer-actual > p:nth-child(2)").html() == "paragraph 2" ',
5), (1,
'Line Breaks', 
'<p>Write line breaks inside of a paragraph. Use sparingly in regular use.</p><p><a href="http://www.w3schools.com/tags/tag_br.asp">Learn about line breaks.</a></p>',
'<p>sentence 1 <br/> sentence 2</p>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > p:nth-child(1)").html().indexOf("<br>") > -1 || $(".answer-actual > p:nth-child(1)").html().indexOf("<br />") > -1 || $(".answer-actual > p:nth-child(1)").html().indexOf("<br/>") > -1',
5), (1,
'Preformatting', 
'<p>Preformatting lets you post code-like text and preserves spacing.</p><p><a href="http://www.w3schools.com/tags/tag_pre.asp">Learn about preformatted text.</a></p>',
'<pre>House  ~  of  ~  Codes</pre>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > pre:nth-child(1)").html() == "House  ~  of  ~  Codes"',
10), (1,
'Block Quotes', 
'<p><blockquote cite="Robert Wilensky">We\'ve heard that a million monkeys at a million keyboards could produce the complete works of Shakespeare; now, thanks to the Internet, we know that is not true.</blockquote</p><p><a href="http://www.w3schools.com/html/html_quotation_elements.asp">Learn about quotations.</a></p>',
'Quote something in a blockquote. I don\t care who or how. Make sure you cite it',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > blockquote:nth-child(1)").attr("cite") != null',
10), (1,
'Comments', 
'<p>Comments let you insert text in code without it affecting how the program runs.</p><p><a href="http://www.w3schools.com/html/html_comments.asp">Learn about comments.</a></p>',
'Write a piece of comment saying: I will comment my code',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual").contents().filter(function(){ return this.nodeType == 8;})[0].data.replace(/ /g, "") == "I will comment my code".replace(/ /g, "")',
5), (1,
'Hyperlinks', 
'<p>Let\'s create a link to "http://stackoverflow.com/". Make sure your link is exact.</p><p><a href="http://www.w3schools.com/html/html_links.asp">Learn about links.</a></p>',
'<a href="http://stackoverflow.com/">Stack Overflow</a>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > a:nth-child(1)").attr("href") == "http://stackoverflow.com/" && $(".answer-actual > a:nth-child(1)").html() == "Stack Overflow"',
5), (1,
'Relative Hyperlinking', 
'<p>Now, let\'s link to the House of Codes logo image, but open it in a new tab. The logo image is called logo.png and sits at the root directory of the server.</p><p><a href="http://www.w3schools.com/html/html_links.asp">Learn about links.</a></p>',
'<a href="/logo.png" target="_blank">Logo in new tab</a>',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > a:nth-child(1)").attr("href") == "/logo.png" && $(".answer-actual > a:nth-child(1)").attr("target") == "_blank"',
10), (1,
'Images', 
'<p>Images can be displayed on screen. Find an image off of the internet and display it.</p><p><a href="http://www.w3schools.com/html/html_images.asp">Learn about images.</a></p>',
'Any image here.',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > img:nth-child(1)").attr("src") != null && $(".answer-actual > img:nth-child(1)").attr("alt") != null',
5), (1,
'Advanced Images', 
'<p>Take an image off the internet and display it here. This time, it has to be exactly 100 pixels tall and 200 pixels wide.</p><p><a href="http://www.w3schools.com/html/html_images.asp">Learn about images.</a></p>',
'Any image here. Just make sure it fits.',
'&lt;div class="panel-body"&gt;',
'&lt;/div&gt;',
'$(".answer-actual > img:nth-child(1)").attr("src") != null && $(".answer-actual > img:nth-child(1)").attr("alt") != null && $(".answer-actual > img:nth-child(1)").attr("height") == "100" && $(".answer-actual > img:nth-child(1)").attr("width") == 200',
10);